# You can modify the following configuration as needed, but don't delete any lines.
# For the file path, if you don't need to set it, just make it an empty string.

jieba:
  HMM: false                  # 是否启用jieba的HMM模型
  tune: true                  # 是否在add_word时自动调整词频
  dictionary: ""              # jieba引擎使用的词典路径
  cut_mode: "default"         # jieba引擎切分语句的方式 default / full / search
  withWeight: false           # 提取关键词时是否返回权重
  allowPOS: "ns n vn v"       # 关键词提取时允许的词性 用空格分隔
  keywords_method: "textrank" # 关键词提取方法 textrank or tfidf
  idf_path: ""                # 使用tfidf方法提取关键词时使用的idf文件路径

thulac:
  model_path: ""              # thulac模型路径
  postag: true                # 是否进行词性标注
  withWeight: false
  allowPOS: "ns n vn v"
  keywords_method: "textrank"
  idf_path: ""

pkuseg:
  model_name: "web"           # pkuseg使用的模型名称 default / web / tourism / medicine / news
  postag: true
  withWeight: false
  allowPOS: "ns n vn v"
  keywords_method: "textrank"
  idf_path: ""

snownlp:

hanlp:
  tok_mode: "coarse"          # 分词模式 fine / coarse
  withWeight: false
  allowPOS: "ns n vn v"
  keywords_method: "textrank"
  idf_path: ""