# You can modify the following configuration as needed, but don't delete any lines.
# For the file path, if you don't need to set it, just make it an empty string.

jieba:
  HMM: false
  tune: true
  withWeight: false
  allowPOS: "ns n vn v" # seperated by space
  dictionary: "" # empty string if not needed
  idf_path: ""
  keywords_method: "textrank" # textrank or tfidf
  cut_mode: "full" # default / full / search

thulac:
  model_path: ""
  t2s: false
  seg_only: false
  max_length: 50000
  keywords_method: "textrank" # textrank or tfidf
  idf_path: ""
  withWeight: false
  allowPOS: "ns n vn v" # seperated by space

pkuseg:
  model_name: "web" # news web medicine tourism default
  postag: true
  keywords_method: "textrank" # textrank or tfidf
  idf_path: ""
  withWeight: false
  allowPOS: "ns n vn v" # seperated by space
  verbose: false

snownlp:
