# You can modify the following configuration as needed, but don't delete any lines.
# For the file path, if you don't need to set it, just make it an empty string.

global:
  multi-engines: true # use other engines while using some method that is not supported by current engine

jieba:
  HMM: true
  filt: false
  tune: true
  topK: 20
  withWeight: false
  allowPOS: "ns n vn v" # seperated by space
  dictionary: ""
  user_dict: "./user_data/user_dict.txt" 
  stop_words: "./user_data/stop_words.txt"
  idf_path: ""
  keyword_extract_method: "textrank" # textrank or tfidf
  cut_mode: "default" # default / full / search

thulac:
  model_path: ""
  user_dict: "./user_data/user_dict.txt"
  stop_words: "./user_data/stop_words.txt"
  t2s: false
  seg_only: false
  filt: false
  topK: 20
  withWeight: false
  max_length: 50000
  keyword_extract_method: "textrank" # textrank or tfidf
  allowPOS: "ns n vn v" # seperated by space
  idf_path: ""

pkuseg:
  model_name: "default"
  user_dict: "default"
  postag: false