# You can modify the following configuration as needed, but don't delete any lines.
# For the file path, if you don't need to set it, just make it an empty string.

log:
  name: "hanseg"
  level: "info" # debug / info / warning / error / critical
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

global:
  multi_engines: true # use other engines while using some method that is not supported by current engine

jieba:
  engine_name: "jieba"
  HMM: true
  filt: true
  tune: true
  topK: 20
  withWeight: false
  allowPOS: "ns n vn v" # seperated by space
  dictionary: "" # empty string if not needed
  user_dict: "user_data/user_dict.txt" # empty string if not needed
  stop_words: "user_data/stop_words.txt" # empty string if not needed
  idf_path: ""
  keywords_method: "textrank" # textrank or tfidf
  cut_mode: "default" # default / full / search

thulac:
  engine_name: "thulac"
  model_path: ""
  user_dict: "user_data/user_dict.txt"
  stop_words: "user_data/stop_words.txt"
  t2s: false
  seg_only: false
  filt: true
  max_length: 50000
  keywords_method: "textrank" # textrank or tfidf
  idf_path: ""
  topK: 20
  withWeight: false
  allowPOS: "ns n vn v" # seperated by space

pkuseg:
  engine_name: "pkuseg"
  model_name: "default"
  user_dict: "default"
  stop_words: "user_data/stop_words.txt"
  filt: true
  postag: true
  keywords_method: "textrank" # textrank or tfidf
  idf_path: ""
  topK: 20
  withWeight: false
  allowPOS: "ns n vn v" # seperated by space